# Generated by Django 3.1.1 on 2022-05-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20220415_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizer',
            name='politicalInterest',
            field=models.CharField(choices=[('Not at all Interested', 'Not at all Interested'), ('Not very Interested', 'Not very Interested'), ('Somewhat Interested', 'Somewhat Interested'), ('Very Interested', 'Very Interested')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilizer',
            name='presidentialCandidate',
            field=models.CharField(choices=[('Joe Biden', 'Joe Biden'), ('Donald Trump', 'Donald Trump'), ('Someone Else', 'Someone Else'), ("I didn't vote", "I didn't vote")], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilizer',
            name='republican',
            field=models.CharField(choices=[('Strong Republican', 'Strong Republican'), ('Not Strong Republican', 'Not Strong Republican'), ('Lean Republican', 'Lean Republican'), ('Independent', 'Independent'), ('Lean Democrat', 'Lean Democrat'), ('Not Strong Democrat', 'Not Strong Democrat'), ('Strong Democrat', 'Strong Democrat')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='utilizer',
            name='confirmationCode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
