# Generated by Django 3.1.1 on 2022-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizer',
            name='qualification',
            field=models.CharField(choices=[('Less than High School', 'Less than High School'), ('High School', 'High School'), ('College Degree', 'College Degree'), ('Doctorate Degree', 'Doctorate Degree'), ('PhD holder', 'PhD holder')], max_length=50),
        ),
    ]
