# Generated by Django 3.2.13 on 2022-05-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20220503_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('Upvote', 'Upvote'), ('Downvote', 'Downvote')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.AlterField(
            model_name='headlines',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='DownVote',
        ),
        migrations.DeleteModel(
            name='UpVote',
        ),
        migrations.AddField(
            model_name='vote',
            name='headline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.headlines'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.utilizer'),
        ),
    ]
