# Generated by Django 3.2.13 on 2022-05-14 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20220514_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
