# Generated by Django 3.2.13 on 2022-05-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20220514_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizer',
            old_name='republican',
            new_name='party',
        ),
    ]
