# Generated by Django 3.2.13 on 2022-05-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_utilizer_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizer',
            name='puceTest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
