# Generated by Django 3.2.13 on 2022-06-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20220531_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generation',
            options={'ordering': ['date_added']},
        ),
        migrations.RenameField(
            model_name='utilizer',
            old_name='GenerationId',
            new_name='generationId',
        ),
        migrations.AddField(
            model_name='vote',
            name='GenerationId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.generation'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
