# Generated by Django 3.2.13 on 2022-06-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20220601_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='prev_gen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.generation'),
        ),
    ]
