# Generated by Django 3.2.13 on 2022-06-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_generation_prev_gen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='prev_gen',
        ),
        migrations.AlterField(
            model_name='generation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
