# Generated by Django 3.2.13 on 2022-06-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20220603_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizer',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utilizer',
            name='qualification',
            field=models.CharField(choices=[('Less than High School', 'Less than High School'), ('High School', 'High School'), ('Bachelor Degree', 'Bachelor Degree'), ('Masters Degree', 'Masters Degree'), ('Doctorate Degree', 'Doctorate Degree')], max_length=50),
        ),
    ]
