# Generated by Django 3.2.13 on 2022-07-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_headlines_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeadLines',
            new_name='Headline',
        ),
    ]
